package br.gov.rj.fazenda.util;

import java.io.IOException;
import java.io.InputStream;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Properties;

import org.apache.log4j.Logger;

import br.gov.rj.fazenda.main.ExecutaProcedures;

public class PropertiesUtil {

	private static final Logger LOGGER = Logger.getLogger(ExecutaProcedures.class.getName() );
	private static Properties prop;
	
	/**
	 /**
	 * @return The Build Timestamp as generated by Maven
	 * @throws IOException
	 */
	public static Properties getProps() throws IOException {
		
		if(prop == null)
		{
			InputStream is = PropertiesUtil.class.getClass().getResourceAsStream("/META-INF/MANIFEST.MF");
			prop = new Properties();
			prop.load(is);
		}
		
		return prop;
	}
	
	/**
	 * Retorna a versao de buid gerado no manifest do JAR
	 * @return
	 * @throws IOException
	 */
	public static String getVersion() throws IOException
	{ 
		return (String) PropertiesUtil.getProps().get("build");
	}
	
	/**
	 * Retorna a versao do jdk usado para o buid
	 * @return
	 * @throws IOException
	 */
	public static String getJDKCompilerBuid() throws IOException
	{ 
		return (String) PropertiesUtil.getProps().get("Build-Jdk");
	}
	
	/**
	 * Retorna o usuario que está executando o JAR
	 */
	public static String getLocalUser()
	{
		return System.getProperty("user.name").toUpperCase();
	}
	
	/**
	 * Retorna o IP do servidor em que o JAR está sendo executado
	 * @return
	 */
	public static String getLocalIP()
	{
		try 
		{
			InetAddress inetAddress = InetAddress.getLocalHost();
			return inetAddress.toString();
        } 
		catch (UnknownHostException ex) 
		{
			return "NAO IDENTIFICADO";
        }
	}
	

	/**
	 * Retorna o autor do buid
	 * @return
	 * @throws IOException
	 */
	public static String getAutorBuid() throws IOException
	{ 
		return (String) PropertiesUtil.getProps().get("Built-By");
	}
	
	
	public static void print() throws IOException
	{
		LOGGER.info("-----------------------------------------------------------------");
		LOGGER.info("---- DADOS DE COMPILACAO DO JOB ---------------------------------");
		LOGGER.info("---- BUILD: " + getVersion());
		LOGGER.info("---- AUTOR: " + getAutorBuid());
		LOGGER.info("---- JDK:   " + getJDKCompilerBuid());
		LOGGER.info("-----------------------------------------------------------------");
		LOGGER.info("---- DADOS DE EXECUCAO ------------------------------------------");
		LOGGER.info("---- IP_SERVER: " + getLocalIP());
		LOGGER.info("---- USUARIO: " + getLocalUser());
		LOGGER.info("-----------------------------------------------------------------");		
	}
}
